#!/bin/bash

set -e

SKIP_TESTS="-DskipTests";
if [ "$1" == "test" ] ; then SKIP_TESTS=""; fi

OLD_BRANCH="$(git rev-parse --abbrev-ref HEAD)  $(git rev-parse HEAD)"
OLD_COMMIT=$(git rev-parse HEAD)

echo -e "\n\n===================================================\n"
echo -e "  Was at branch: $OLD_BRANCH"
echo -e "  Switching to master and pulling.\n"
echo -e "===================================================\n"
## Fetches new commits, pulls master and rebuilds, without tests.
mvn clean
echo -e "\n\n===================================================\n"
echo -e "  Was at branch: $OLD_BRANCH"
echo -e "  Switching to master and pulling.\n"
echo -e "===================================================\n"
git fetch --all
git checkout master
git branch --set-upstream-to=upstream/master master
git pull --ff-only
mvn clean install $SKIP_TESTS
git log --abbrev=4 --pretty=oneline --graph ${OLD_COMMIT}..upstream/master

echo -e "\n==================================================="
echo -e "\n    Previous branch was: " $OLD_BRANCH
echo -e "\n===================================================\n"

