#!/bin/bash
set -e

##  Usage:
# reWeb web
# reWeb ser
# reWeb both == reWeb x

WHAT="$1"
shift
SER="1"
WEB="1"
RF="" ## Resume from

if [ "$WHAT" == "all" ] ;  then ALL="1" ; fi
if [ "$WHAT" == "ser" ] ;  then WEB="" ; fi
if [ "$WHAT" == "rest" ] ; then SER="1"; WEB=""; RF="-rf services"; fi
if [ "$WHAT" == "web" ] ;  then SER="" ; fi
if [ "$WHAT" == "ui" ] ;   then SER="" ; fi
if [ "$WHAT" == "js" ] ;   then SER=""; WEB=""; fi

#if [ "$SER" != "" ] ; then echo "Sending to WildFly: '$CMD_SER'"; runWF10cli --connect --command="$CMD_SER"; fi
#if [ "$WEB" != "" ] ; then echo "Sending to WildFly: '$CMD_WEB'"; runWF10cli --connect --command="$CMD_WEB"; fi


pushd .


if [ "$ALL" != "" ] ; then
  ### Build the whole web
  cd ~/work/mig/windup-web/
  mvn clean install -DskipTests "$@" #-PtscNoFail
  echo -e "\n\n==================\n\n"
  ~/sc/windup/redeploy
  echo -e "\n\n"
elif [ "$SER" != "" ] ; then
  ### Build addons and services
  cd ~/work/mig/windup-web/
  mvn clean install -DskipTests --also-make-dependents -pl addons,services $RF "$@"
  echo -e "\n\n==================\n\n"
  ~/sc/windup/redeploy ser
  echo -e "\n\n"
elif [ "$WHAT" == "js" ] ; then
  ~/sc/windup/rePack
else
  ### Only UI
  cd ~/work/mig/windup-web/ui
  mvn clean install -DskipTests #-PtscNoFail #wildfly:undeploy wildfly:deploy-only
  echo -e "\n\n==================\n\n"
  ~/sc/windup/redeploy ui
  echo -e "\n\n"
fi

echo "Build finished at " $(date '+%Y-%m-%d %H:%M:%S') ""



popd
