#! /bin/bash
# Multi command start in various Konsole tabs

# List of commands to run, with parameters, in quotes, space-separated; do not use quotes inside (see bash arrays)
COMMANDS=("~/sc/windup/runRHSSO7" "runWF10 #--debug" "~/sc/cdWindupWeb && git fetch" "~/sc/cdWindupWebApp")

## Let's get the console service
# KDS=$KONSOLE_DBUS_SERVICE # Reference to current Konsole, only works in Konsole
qdbus >/tmp/q0              # Get the current list of konsoles
/usr/bin/konsole            # Launch a new konsole
sleep 1
# PID=$!                    # And get its PID - But for some reason this is not the right PID.
# KDS=org.kde.konsole-$PID      
# KDS=org.kde.konsole       # Sometimes
qdbus >/tmp/q1              # Get the new list of konsoles
KDS=$(diff /tmp/q{0,1} | grep konsole)  # Let's hope there's only one
KDS=${KDS:3}                # Strip the first 3 chars (diff status)
echo "KDS: $KDS"
echo -e "$KDS\n" >/tmp/KDS

qdbus $KDS >>/tmp/KDS || exit
echo >>/tmp/KDS

# See note https://docs.kde.org/trunk5/en/applications/konsole/scripting.html about using /Konsole
qdbus $KDS /konsole >>/tmp/KDS
echo >>/tmp/KDS

whichSession=currentSession

for i in "${COMMANDS[@]}"; do 
    echo -e "Starting in Konsole: $i\n"
    #session=$(qdbus $KDS /Konsole $whichSession)
    #whichSession=newSession
    session=1

    # Test: Display possible actions
    qdbus $KDS /Sessions/${session} >>/tmp/KDS

    # Doesn't work well, maybe use setTabTitleFormat 0/1 instead
    # Title "0" appears to be the initial title, title "1" is the title used after commands are executed. 
    #qdbus $KDS /Sessions/${session} setTitle 0 $i
    #qdbus $KDS /Sessions/${session} setTitle 1 $i

    # The line break is necessary to commit the command. \n doesn't work
    #qdbus $KDS /Sessions/${session} sendText "${i}
#"
    qdbus $KDS /Sessions/${session} runComand "${i}"
    # Optional: will ping when there's no more output in the window
    qdbus $KDS /Sessions/${session} setMonitorSilence true
done
